config/routes.rb
Assignment::Application.routes.draw do
  
  get "home/logout"
  match 'home/logout' => 'home#logout'
  get "home/index"

  get "home/login"

  match 'authenticate' => 'home#authenticate'

  resources :recipes

  resources :user_profiles

  resources :users

   root :to => "home#index"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :user_profile
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
    def protect
    if session[:user].nil?
      flash[:notice] = "You must be logged in to access this section"
      redirect_to :controller => "home", :action => "index"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
  end

  def login
  end

  def authenticate
    puts "welcome  we"
    puts params[:user_name]
    puts params[:password]
    @user=User.find_by_user_name_and_password(params[:user_name],params[:password])
    
    if @user
      session[:user]=@user.id
      redirect_to (@user,:notice => "User #{@user.user_name}  Loggedin")
    else
      flash[:notice] = "User name or Password is wrong"
      redirect_to :back
    end
  end

def logout
      session[:user]=nil
      flash[:notice] = "Successfully logedout"
      redirect_to :controller => "home", :action => "index"
end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :protect
  
  # GET /recipes
  # GET /recipes.xml
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @user=User.find(session[:user])
    params[:recipe][:user_id]=session[:user]
    params[:recipe][:user_name]=@user.user_name
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(recipes_path, :notice => 'Recipe was successfully created.') }
        format.xml  { render :xml => recipes_path, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_filter :protect
  # GET /user_profiles
  # GET /user_profiles.xml
  def index
    @user_profiles = UserProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_profiles }
    end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.xml
  def show
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.xml
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.xml
  def create
    params[:user_profile][:user_id]=session[:user]
    @user_profile = UserProfile.new(params[:user_profile])
    @user=User.find(session[:user])
    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to(@user, :notice => 'User profile was successfully created.') }
        
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.xml
  def update
    @user_profile = UserProfile.find(params[:id])
    @user=User.find(session[:user])
    respond_to do |format|
      if @user_profile.update_attributes(params[:user_profile])
        format.html { redirect_to(@user, :notice => 'User profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.xml
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to(user_profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :protect, :except => [:new, :create]
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user]=@user.id
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_login.html.erb
<table>
<form name="login" action="/authenticate" method="post"> 
<tr><td>User Name :</td><td><input type="text" name="user_name" /></td></tr>
<tr><td>Password :</td><td><input type="password" name="password" /></td></tr>
<tr><td><input type="submit" value="Login" /></td></tr>
</form>
</table>

app/views/home/authenticate.html.erb
<h1>Home#authenticate</h1>
<p>Find me in app/views/home/authenticate.html.erb</p>

app/views/home/index.html.erb
<div style="padding:10px;"><h1>Welcome to Recipe Management System</h1></div>
<p id="notice"><%= notice %></p>
<table cellpadding="20px" cellspacing="0" border="1">
<tr>
	<td>
	<h1>New User Signup</h1>
	<%= render '/users/form' %>
	</td>
    <td>
	<h1>User Login</h1>
	<%= render '/home/login' %>
    </td>
</tr></table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% if session[:user] %>
	<div align=right style="padding:10px">
		<%= button_to "Logout", :controller => :home, :action => :logout %>
	</div>
<% end%>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_veg %><br />
    <%= f.check_box :is_veg %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :sub_category %><br />
    <%= f.text_field :sub_category %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_field :video %>
  </div>
  <div class="field">
    <%= f.label :steps %><br />
    <%= f.text_field :steps %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_field :comments %>
  </div>
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table cellspacing="0" cellpadding="10px" border="1">
  <tr>
    <th>S No</th>
    <th>User name</th>
    <th>Name</th>
    <th>Rating</th>
    <th colspan="3">Actions</th>
  </tr>

<% @recipes.each_with_index do |recipe, index| %>
  <tr>
    <td><%= index+1 %></td>
    <td><%= recipe.user_name %></td>
    <td><%= link_to recipe.name, recipe %></td>
    <td><%= recipe.rating %></td>

    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />




<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @recipe.user_id %>
</p>

<p>
  <b>User name:</b>
  <%= @recipe.user_name %>
</p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Is veg:</b>
  <%= @recipe.is_veg %>
</p>

<p>
  <b>Category:</b>
  <%= @recipe.category %>
</p>
<p>
  <b>Sub Category:</b>
  <%= @recipe.sub_category %>
</p>
<p>
  <b>Steps:</b>
  <%= @recipe.steps %>
</p>
<p>
  <b>Comments:</b>
  <%= @recipe.comments %>
</p>
<p>
  <b>Tag:</b>
  <%= @recipe.tag %>
</p>
  <b>Rating:</b>
  <%= @recipe.rating %>
</p>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :profile_name %><br />
    <%= f.text_field :profile_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <tr>
    <th>User</th>
    <th>Profile name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Mobile</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_profiles.each do |user_profile| %>
  <tr>
    <td><%= user_profile.user_id %></td>
    <td><%= user_profile.profile_name %></td>
    <td><%= user_profile.address %></td>
    <td><%= user_profile.phone %></td>
    <td><%= user_profile.mobile %></td>
    <td><%= link_to 'Show', user_profile %></td>
    <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
    <td><%= link_to 'Destroy', user_profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Profile name:</b>
  <%= @user_profile.profile_name %>
</p>

<p>
  <b>Address:</b>
  <%= @user_profile.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @user_profile.phone %>
</p>

<p>
  <b>Mobile:</b>
  <%= @user_profile.mobile %>
</p>


<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Role</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.user_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<fieldset>
<legend>User's Home'</legend>
<% if @user.user_profile.blank? %>
<%= link_to "User Profile",  new_user_profile_path%><br />
<% else %>
<%= link_to "User Profile",  edit_user_profile_path(@user)%><br />
<% end %>

<%= link_to "Manage Recipe",  recipes_path%><br />
<%= link_to "Create  New Recipe",  new_recipe_path%><br />
 
</fieldset>












<p>
  <b>User name:</b>
  <%= @user.user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>